/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HBFTelas;


import Model.Vendas;
import Conexao.ConectorMySql;
import Controller.FornecedorController;
import Controller.ProdutoController;
import Controller.VendasController;
import Model.Categorias;
import Model.Cliente;
import Model.FormaPagto;
import Model.Fornecedor;
import Model.Geral;
import Model.ItemVenda;
import Model.Produto;
import Model.TipoVenda;
import com.mysql.jdbc.StringUtils;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Hudson
 */
public class CadastroVendas extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroVendas
     */
    
    private int idVendaAtual = 0;
    private int idProdutoClicado = 0;
    Vendas venda = new Vendas();
    Cliente cliente = new Cliente();
    FormaPagto formapagto = new FormaPagto();
    TipoVenda tipovenda = new TipoVenda();
    Produto produto = new Produto();
    
    List<ItemVenda> item = null;
    DecimalFormat valorFormatado = new DecimalFormat("0.00");
    SimpleDateFormat dataFormatadaExibir = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat dataFormatadaSalvar = new SimpleDateFormat("yyMMdd");
    //DateFormat outputFormat = new SimpleDateFormat("MM/yyyy");
    //DateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSX");
    
    public CadastroVendas() {
        initComponents();
        if(idVendaAtual != 0){
            preencheTabela(idVendaAtual);
        }
        //Connection con = ConectorMySql.getConnection();
        //PreparedStatement stmt = null;
        
    }
    
    public void preencheTabela(int codVenda){
        
        DefaultTableModel prod = (DefaultTableModel)tabelaProdutos.getModel();
        tabelaProdutos.setRowSorter(new TableRowSorter(prod));
        VendasController contr = new VendasController();
        prod.setNumRows(0);
        item = contr.selectItensVenda(codVenda);
        for(int i=0;i<item.size();i++){
            prod.addRow(new Object[]{item.get(i).getCodProduto(), item.get(i).getNomeProd(), item.get(i).getQuantidade(), valorFormatado.format(item.get(i).getValorUnit()), valorFormatado.format(item.get(i).getValorTotal()), item.get(i).getIdVendaxproduto()});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        campoCodVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoCodCliente = new javax.swing.JTextField();
        campoTipoVenda = new javax.swing.JTextField();
        campoFormaPagto = new javax.swing.JTextField();
        botaoPesquisaVenda = new javax.swing.JButton();
        botaoPesquisaCliente = new javax.swing.JButton();
        botaoPesquisaTipoVenda = new javax.swing.JButton();
        botaoPesquisaFormaPagto = new javax.swing.JButton();
        campoNomeCliente = new javax.swing.JTextField();
        campoNomeTipoVenda = new javax.swing.JTextField();
        campoNomeFormaPagto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoTotalVenda = new javax.swing.JTextField();
        botaoGravarVenda = new javax.swing.JButton();
        botaoIncluir = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        campoCodProduto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoNomeProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoQntProduto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        campoValorUnitProduto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoValorTotalProduto = new javax.swing.JTextField();
        botaoIncluirProduto = new javax.swing.JButton();
        botaoExcluirProduto = new javax.swing.JButton();
        botaoCancelarProduto = new javax.swing.JButton();
        botaoGravarProduto = new javax.swing.JButton();
        botaoPesquisarProduto = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        campoDataVenda = new org.jdesktop.swingx.JXDatePicker();

        setClosable(true);
        setIconifiable(true);
        setTitle("Controle de Vendas");

        jLabel1.setText("Cód.Venda:");

        campoCodVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodVendaFocusLost(evt);
            }
        });
        campoCodVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodVendaActionPerformed(evt);
            }
        });

        jLabel2.setText("Data:");

        jLabel3.setText("Cód.Cliente:");

        jLabel4.setText("Cód.Tipo Venda:");

        jLabel5.setText("Cód.Forma Pagamento:");

        campoCodCliente.setEnabled(false);
        campoCodCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodClienteFocusLost(evt);
            }
        });
        campoCodCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodClienteActionPerformed(evt);
            }
        });

        campoTipoVenda.setEnabled(false);
        campoTipoVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTipoVendaFocusLost(evt);
            }
        });

        campoFormaPagto.setEnabled(false);
        campoFormaPagto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoFormaPagtoFocusLost(evt);
            }
        });

        botaoPesquisaVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        botaoPesquisaVenda.setContentAreaFilled(false);
        botaoPesquisaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisaVendaActionPerformed(evt);
            }
        });

        botaoPesquisaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        botaoPesquisaCliente.setContentAreaFilled(false);
        botaoPesquisaCliente.setEnabled(false);
        botaoPesquisaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisaClienteActionPerformed(evt);
            }
        });

        botaoPesquisaTipoVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        botaoPesquisaTipoVenda.setContentAreaFilled(false);
        botaoPesquisaTipoVenda.setEnabled(false);
        botaoPesquisaTipoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisaTipoVendaActionPerformed(evt);
            }
        });

        botaoPesquisaFormaPagto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        botaoPesquisaFormaPagto.setContentAreaFilled(false);
        botaoPesquisaFormaPagto.setEnabled(false);
        botaoPesquisaFormaPagto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisaFormaPagtoActionPerformed(evt);
            }
        });

        campoNomeCliente.setEditable(false);
        campoNomeCliente.setEnabled(false);

        campoNomeTipoVenda.setEditable(false);
        campoNomeTipoVenda.setEnabled(false);

        campoNomeFormaPagto.setEditable(false);
        campoNomeFormaPagto.setEnabled(false);

        jLabel6.setText("Produtos:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Total Venda R$:");

        campoTotalVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoTotalVenda.setEnabled(false);
        campoTotalVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTotalVendaActionPerformed(evt);
            }
        });

        botaoGravarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gravar.png"))); // NOI18N
        botaoGravarVenda.setText("Gravar Venda");
        botaoGravarVenda.setEnabled(false);
        botaoGravarVenda.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                botaoGravarVendaInputMethodTextChanged(evt);
            }
        });
        botaoGravarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGravarVendaActionPerformed(evt);
            }
        });

        botaoIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Novo.png"))); // NOI18N
        botaoIncluir.setText("Incluir");
        botaoIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirActionPerformed(evt);
            }
        });

        botaoExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.setEnabled(false);
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Editar.png"))); // NOI18N
        botaoEditar.setText("Editar");
        botaoEditar.setEnabled(false);
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cancelar.png"))); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.setEnabled(false);
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Quantidade", "Valor Unitário", "Valor Total"
            }
        ));
        tabelaProdutos.setEnabled(false);
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        tabelaProdutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaProdutosKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaProdutos);

        jLabel8.setText("Cód:");

        campoCodProduto.setEnabled(false);
        campoCodProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCodProdutoFocusLost(evt);
            }
        });

        jLabel9.setText("Descrição:");

        campoNomeProduto.setEditable(false);
        campoNomeProduto.setEnabled(false);

        jLabel10.setText("Quantidade:");

        campoQntProduto.setEnabled(false);
        campoQntProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoQntProdutoFocusLost(evt);
            }
        });
        campoQntProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoQntProdutoActionPerformed(evt);
            }
        });

        jLabel11.setText("Valor Unitário:");

        campoValorUnitProduto.setEnabled(false);
        campoValorUnitProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoValorUnitProdutoFocusLost(evt);
            }
        });
        campoValorUnitProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoValorUnitProdutoActionPerformed(evt);
            }
        });

        jLabel12.setText("Valor Total:");

        campoValorTotalProduto.setEnabled(false);
        campoValorTotalProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoValorTotalProdutoFocusLost(evt);
            }
        });

        botaoIncluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NovoPequeno.png"))); // NOI18N
        botaoIncluirProduto.setText("Incluir");
        botaoIncluirProduto.setEnabled(false);
        botaoIncluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIncluirProdutoActionPerformed(evt);
            }
        });

        botaoExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ExcluirPequeno.png"))); // NOI18N
        botaoExcluirProduto.setText("Excluir");
        botaoExcluirProduto.setEnabled(false);
        botaoExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirProdutoActionPerformed(evt);
            }
        });

        botaoCancelarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CancelarPequeno.png"))); // NOI18N
        botaoCancelarProduto.setText("Cancelar");
        botaoCancelarProduto.setEnabled(false);
        botaoCancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarProdutoActionPerformed(evt);
            }
        });

        botaoGravarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/GravarPequeno.png"))); // NOI18N
        botaoGravarProduto.setText("Gravar");
        botaoGravarProduto.setEnabled(false);
        botaoGravarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoGravarProdutoActionPerformed(evt);
            }
        });

        botaoPesquisarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        botaoPesquisarProduto.setContentAreaFilled(false);
        botaoPesquisarProduto.setEnabled(false);
        botaoPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarProdutoActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LogoFundo.png"))); // NOI18N

        campoDataVenda.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(botaoIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(botaoGravarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoPesquisaFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNomeFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoTipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botaoPesquisaTipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoNomeTipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(campoCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(botaoPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(campoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(campoCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(botaoPesquisaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(campoDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(134, 134, 134)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botaoIncluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botaoGravarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botaoCancelarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botaoExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel12)))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(campoCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(botaoPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoValorTotalProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(campoQntProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel11)
                                                .addGap(4, 4, 4)
                                                .addComponent(campoValorUnitProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoGravarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(campoCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(botaoPesquisaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addComponent(campoNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botaoPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoTipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addComponent(campoNomeTipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botaoPesquisaTipoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNomeFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(campoFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addComponent(botaoPesquisaFormaPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoIncluirProduto)
                            .addComponent(botaoGravarProduto))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoCancelarProduto)
                            .addComponent(botaoExcluirProduto))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel10)
                                .addGap(17, 17, 17)
                                .addComponent(jLabel12))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botaoPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)
                                .addComponent(campoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoQntProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel11))
                                    .addComponent(campoValorUnitProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(campoValorTotalProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))))
        );

        setBounds(10, 10, 966, 585);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void botaoGravarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGravarVendaActionPerformed
        // TODO add your handling code here:
      if(!(campoNomeCliente.getText()).isEmpty() && !(campoNomeTipoVenda.getText()).isEmpty() && !(campoNomeFormaPagto.getText()).isEmpty() && !(campoDataVenda.getDate() == null)){
        Vendas v = new Vendas();
        VendasController contr = new VendasController();
        /*String teste = dataFormatadaSalvar.format(campoDataVenda.getText());
        
        JOptionPane.showMessageDialog(null,teste);
        
        JOptionPane.showMessageDialog(null,(dataFormatadaSalvar.format(teste)).toString());
        
        v.setDataVenda((dataFormatadaSalvar.format(teste)).toString());*/
        v.setDataVenda(campoDataVenda.getDate());
        
        
        //v.setDataVenda(campoDataVenda.getText());
        v.setIdCliente(Integer.parseInt(campoCodCliente.getText()));
        v.setIdTipoVenda(Integer.parseInt(campoTipoVenda.getText()));
        v.setIdFormaPagto(Integer.parseInt(campoFormaPagto.getText()));

        if(idVendaAtual > 0){
            contr.update(v, idVendaAtual);
        }else{
            contr.create(v);
            idVendaAtual = contr.ultimoId();
        }
        
        campoCodVenda.setText(Integer.toString(idVendaAtual));
        campoCodVenda.setEnabled(true);
        botaoPesquisaVenda.setEnabled(true);
        campoCodCliente.setEnabled(false);
        campoNomeCliente.setEnabled(true);
        botaoPesquisaCliente.setEnabled(false);
        campoTipoVenda.setEnabled(false);
        campoNomeTipoVenda.setEnabled(true);
        botaoPesquisaTipoVenda.setEnabled(false);
        campoFormaPagto.setEnabled(false);
        campoNomeFormaPagto.setEnabled(true);
        botaoPesquisaFormaPagto.setEnabled(false);
        campoDataVenda.setEnabled(true);
        campoDataVenda.setEditable(false);
        campoTotalVenda.setEnabled(true);
        campoTotalVenda.setEditable(false);
        botaoCancelar.setEnabled(false);
        botaoGravarVenda.setEnabled(false);
        botaoIncluir.setEnabled(true);
        botaoSair.setEnabled(true);
        botaoEditar.setEnabled(true);
        if(Geral.UsuarioLogado.getTipo().equals("Usuário"))
        {
            botaoExcluir.setEnabled(false);
        }
        else{
            botaoExcluir.setEnabled(true);
        }
        
        botaoIncluirProduto.setEnabled(false);
        botaoExcluirProduto.setEnabled(false);
        botaoCancelarProduto.setEnabled(false);
	botaoGravarProduto.setEnabled(false);
        botaoPesquisarProduto.setEnabled(false);
        
        tabelaProdutos.setEnabled(false);
        preencheTabela(idVendaAtual);
        
        v = null;
        contr = null;
        
      }else{
          JOptionPane.showMessageDialog(null,"Preenchimento de todos os campos obrigatório !");
      }
        
    }//GEN-LAST:event_botaoGravarVendaActionPerformed

    private void botaoIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirActionPerformed
        // TODO add your handling code here:
        
        campoCodVenda.setText("");
        campoCodCliente.setText("");
        campoNomeCliente.setText("");
        campoTipoVenda.setText("");
        campoNomeTipoVenda.setText("");
        campoFormaPagto.setText("");
        campoNomeFormaPagto.setText("");
        //campoDataVenda.removeAll();
        campoTotalVenda.setText("");
        
        
        campoCodVenda.setEnabled(false);
        botaoPesquisaVenda.setEnabled(false);
        campoCodCliente.setEnabled(true);
        campoNomeCliente.setEnabled(false);
        botaoPesquisaCliente.setEnabled(true);
        campoTipoVenda.setEnabled(true);
        campoNomeTipoVenda.setEnabled(false);
        botaoPesquisaTipoVenda.setEnabled(true);
        campoFormaPagto.setEnabled(true);
        campoNomeFormaPagto.setEnabled(false);
        botaoPesquisaFormaPagto.setEnabled(true);
        campoDataVenda.setEnabled(true);
        campoDataVenda.setEditable(true);
        campoTotalVenda.setEnabled(false);
        campoTotalVenda.setEditable(false);
        botaoCancelar.setEnabled(true);
        botaoGravarVenda.setEnabled(true);
        botaoIncluir.setEnabled(false);
        botaoEditar.setEnabled(false);
        botaoExcluir.setEnabled(false);
        botaoSair.setEnabled(false);
        
        campoCodProduto.setText("");
        campoNomeProduto.setText("");
        campoQntProduto.setText("");
        campoValorUnitProduto.setText("");
        campoValorTotalProduto.setText("");
        
        campoCodProduto.setEnabled(false);
        campoNomeProduto.setEnabled(false);
        campoQntProduto.setEnabled(false);
        campoValorUnitProduto.setEnabled(false);
        campoValorTotalProduto.setEnabled(false);
        botaoIncluirProduto.setEnabled(false);
        botaoExcluirProduto.setEnabled(false);
        botaoCancelarProduto.setEnabled(false);
        botaoGravarProduto.setEnabled(false);
        botaoPesquisarProduto.setEnabled(false);
                
        idVendaAtual = 0;
        tabelaProdutos.setEnabled(true);
        preencheTabela(idVendaAtual);
        
    }//GEN-LAST:event_botaoIncluirActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        // TODO add your handling code here:
        campoCodVenda.setEnabled(true);
        botaoPesquisaVenda.setEnabled(true);
        campoCodCliente.setEnabled(false);
        botaoPesquisaCliente.setEnabled(false);
        campoTipoVenda.setEnabled(false);
        botaoPesquisaTipoVenda.setEnabled(false);
        campoFormaPagto.setEnabled(false);
        botaoPesquisaFormaPagto.setEnabled(false);
        campoDataVenda.setEnabled(false);
        campoTotalVenda.setEnabled(false);
        botaoCancelar.setEnabled(false);
        botaoGravarVenda.setEnabled(false);
        botaoIncluir.setEnabled(true);
        botaoSair.setEnabled(true);
        
        campoCodVenda.setText("");
        campoCodCliente.setText("");
        campoNomeCliente.setText("");
        campoTipoVenda.setText("");
        campoNomeTipoVenda.setText("");
        campoFormaPagto.setText("");
        campoNomeFormaPagto.setText("");
        //campoDataVenda.removeAll();
        campoTotalVenda.setText("");
        
        campoCodProduto.setText("");
        campoNomeProduto.setText("");
        campoQntProduto.setText("");
        campoValorUnitProduto.setText("");
        campoValorTotalProduto.setText("");
        
        campoCodProduto.setEnabled(false);
        campoNomeProduto.setEnabled(false);
        campoQntProduto.setEnabled(false);
        campoValorUnitProduto.setEnabled(false);
        campoValorTotalProduto.setEnabled(false);
        botaoIncluirProduto.setEnabled(false);
        botaoExcluirProduto.setEnabled(false);
        botaoCancelarProduto.setEnabled(false);
        botaoGravarProduto.setEnabled(false);
        botaoPesquisarProduto.setEnabled(false);
        
        
        idVendaAtual = 0;
        tabelaProdutos.setEnabled(false);
        preencheTabela(idVendaAtual);
        
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
        idVendaAtual = 0;
        dispose();
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoPesquisaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisaVendaActionPerformed
        // TODO add your handling code here:
        /*if(!(campoCodVenda.getText()).isEmpty()){
            ArrayList dados;
            Vendas v = new Vendas();
            VendasController contr = new VendasController();
            v.setIdVenda(Integer.parseInt(campoCodVenda.getText()));
            dados = contr.pesquisaVenda(v.getIdVenda());
            if(dados != null){
                campoNomeCliente.setEnabled(true);
                campoNomeTipoVenda.setEnabled(true);
                campoNomeFormaPagto.setEnabled(true);
                campoDataVenda.setEnabled(true);
                campoDataVenda.setEditable(false);
                campoTotalVenda.setEnabled(true);
                campoTotalVenda.setEditable(false);
                botaoEditar.setEnabled(true);
                if(Geral.UsuarioLogado.getTipo().equals("Usuário")){
                    botaoExcluir.setEnabled(false);
                }
                else{
                    botaoExcluir.setEnabled(true);
                }

                campoDataVenda.setText(dataFormatadaExibir.format(dados.get(0)));
                campoCodCliente.setText((String)dados.get(1));
                campoTotalVenda.setText(valorFormatado.format(dados.get(2)));
                campoTipoVenda.setText((String)dados.get(3));
                campoFormaPagto.setText((String)dados.get(4));
                campoNomeCliente.setText((String)dados.get(5));
                campoNomeTipoVenda.setText((String)dados.get(6));
                campoNomeFormaPagto.setText((String)dados.get(7));
                idVendaAtual = v.getIdVenda();
                tabelaProdutos.setEnabled(false);
                preencheTabela(idVendaAtual);
            }else{
                campoCodCliente.setText("");
                campoNomeCliente.setText("");
                campoTipoVenda.setText("");
                campoNomeTipoVenda.setText("");
                campoFormaPagto.setText("");
                campoNomeFormaPagto.setText("");
                campoDataVenda.setText("");
                campoTotalVenda.setText("");
                campoNomeCliente.setEnabled(false);
                campoNomeTipoVenda.setEnabled(false);
                campoNomeFormaPagto.setEnabled(false);
                campoDataVenda.setEnabled(false);
                campoTotalVenda.setEnabled(false);
                botaoEditar.setEnabled(false);
                botaoExcluir.setEnabled(false);
                
                botaoIncluirProduto.setEnabled(false);
                botaoExcluirProduto.setEnabled(false);
                botaoCancelarProduto.setEnabled(false);
                botaoGravarProduto.setEnabled(false);
                botaoPesquisarProduto.setEnabled(false);
                
                campoCodVenda.requestFocus();
                
                idVendaAtual = 0;
                preencheTabela(idVendaAtual);
                
                JOptionPane.showMessageDialog(null,"Código de Venda não localizado");
            }
            v = null;
            contr = null;
        }*/

        ConsultaVenda consultavenda = new ConsultaVenda(venda);
        
        consultavenda.addWindowListener(new WindowListener() {
           @Override
           public void windowOpened(WindowEvent e) {
           }

           @Override
           public void windowClosing(WindowEvent e) {
           }

           @Override
           public void windowClosed(WindowEvent e) {
               
                venda = consultavenda.GetVendas();
                
                
                if(venda.getIdVenda() > 0){
                Vendas dados;
                //Vendas v = new Vendas();
                VendasController contr = new VendasController();
                //v.setIdVenda(Integer.parseInt(campoCodVenda.getText()));
                //dados = contr.pesquisaVenda(v.getIdVenda());
                dados = contr.pesquisaVenda(venda.getIdVenda());
                if(dados != null){
                    campoNomeCliente.setEnabled(true);
                    campoNomeTipoVenda.setEnabled(true);
                    campoNomeFormaPagto.setEnabled(true);
                    campoDataVenda.setEnabled(true);
                    campoDataVenda.setEditable(false);
                    campoTotalVenda.setEnabled(true);
                    campoTotalVenda.setEditable(false);
                    botaoEditar.setEnabled(true);
                    if(Geral.UsuarioLogado.getTipo().equals("Usuário")){
                        botaoExcluir.setEnabled(false);
                    }
                    else{
                        botaoExcluir.setEnabled(true);
                    }

                    campoCodVenda.setText(Integer.toString(venda.getIdVenda()));
                    campoDataVenda.setDate(dados.getDataVenda());
                    campoCodCliente.setText(Integer.toString(dados.getIdCliente()));
                    campoTotalVenda.setText(valorFormatado.format(dados.getValorTotal()));
                    campoTipoVenda.setText(Integer.toString(dados.getIdTipoVenda()));
                    campoFormaPagto.setText(Integer.toString(dados.getIdFormaPagto()));
                    campoNomeCliente.setText(dados.getNomeCliente());
                    campoNomeTipoVenda.setText(dados.getNomeTipoVenda());
                    campoNomeFormaPagto.setText(dados.getNomeFormaPagto());
                    idVendaAtual = venda.getIdVenda();
                    tabelaProdutos.setEnabled(false);
                    preencheTabela(idVendaAtual);
                }else{
                    campoCodCliente.setText("");
                    campoNomeCliente.setText("");
                    campoTipoVenda.setText("");
                    campoNomeTipoVenda.setText("");
                    campoFormaPagto.setText("");
                    campoNomeFormaPagto.setText("");
                    //campoDataVenda.removeAll();
                    campoTotalVenda.setText("");
                    campoNomeCliente.setEnabled(false);
                    campoNomeTipoVenda.setEnabled(false);
                    campoNomeFormaPagto.setEnabled(false);
                    campoDataVenda.setEnabled(false);
                    campoTotalVenda.setEnabled(false);
                    botaoEditar.setEnabled(false);
                    botaoExcluir.setEnabled(false);

                    botaoIncluirProduto.setEnabled(false);
                    botaoExcluirProduto.setEnabled(false);
                    botaoCancelarProduto.setEnabled(false);
                    botaoGravarProduto.setEnabled(false);
                    botaoPesquisarProduto.setEnabled(false);

                    campoCodVenda.requestFocus();

                    idVendaAtual = 0;
                    preencheTabela(idVendaAtual);

                    JOptionPane.showMessageDialog(null,"Código de Venda não localizado");
                }
                contr = null;
            }
               
           }

           @Override
           public void windowIconified(WindowEvent e) {
           }

           @Override
           public void windowDeiconified(WindowEvent e) {
           }

           @Override
           public void windowActivated(WindowEvent e) {
           }

           @Override
           public void windowDeactivated(WindowEvent e) {
           }
       });
       consultavenda.setVisible(true);
        
    }//GEN-LAST:event_botaoPesquisaVendaActionPerformed

    private void campoCodVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodVendaActionPerformed

    private void botaoPesquisaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisaClienteActionPerformed
        // TODO add your handling code here:
        /*String dados;
        Vendas v = new Vendas();
        VendasController contr = new VendasController();
        v.setIdCliente(Integer.parseInt(campoCodCliente.getText()));
        dados = contr.pesquisaCliente(v.getIdCliente());
        if( dados != null){
            campoNomeCliente.setText(dados);
        }else{
            campoNomeCliente.setText("");
            JOptionPane.showMessageDialog(null,"Código de Cliente não localizado");
        }
        v = null;
        contr = null;*/
        
        ConsultaCliente consultacliente = new ConsultaCliente(cliente);
        
        consultacliente.addWindowListener(new WindowListener() {
           @Override
           public void windowOpened(WindowEvent e) {
           }

           @Override
           public void windowClosing(WindowEvent e) {
           }

           @Override
           public void windowClosed(WindowEvent e) {
               
                cliente = consultacliente.GetCliente();
                
                
                if(cliente.getCodigo() > 0){
                    String dados;
                    //Vendas v = new Vendas();
                    VendasController contr = new VendasController();
                    //v.setIdCliente(Integer.parseInt(campoCodCliente.getText()));
                    //dados = contr.pesquisaCliente(v.getIdCliente());
                    dados = contr.pesquisaCliente(cliente.getCodigo());
                    if( dados != null){
                        campoNomeCliente.setText(dados);
                        campoCodCliente.setText(Integer.toString(cliente.getCodigo()));
                    }else{
                        campoNomeCliente.setText("");
                        JOptionPane.showMessageDialog(null,"Código de Cliente não localizado");
                    }
                    //v = null;
                    contr = null;
                }
               
           }

           @Override
           public void windowIconified(WindowEvent e) {
           }

           @Override
           public void windowDeiconified(WindowEvent e) {
           }

           @Override
           public void windowActivated(WindowEvent e) {
           }

           @Override
           public void windowDeactivated(WindowEvent e) {
           }
       });
       consultacliente.setVisible(true);
        
    }//GEN-LAST:event_botaoPesquisaClienteActionPerformed

    private void botaoPesquisaTipoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisaTipoVendaActionPerformed
        // TODO add your handling code here:
        /*String dados;
        Vendas v = new Vendas();
        VendasController contr = new VendasController();
        v.setIdTipoVenda(Integer.parseInt(campoTipoVenda.getText()));
        dados = contr.pesquisaTipoVenda(v.getIdTipoVenda());
        if( dados != null){
            campoNomeTipoVenda.setText(dados);
        }else{
            campoNomeTipoVenda.setText("");
            JOptionPane.showMessageDialog(null,"Código de Tipo de Venda não localizado");
        }
        v = null;
        contr = null;*/
        
        ConsultaTipoVenda consultatipovenda = new ConsultaTipoVenda(tipovenda);
        
        consultatipovenda.addWindowListener(new WindowListener() {
           @Override
           public void windowOpened(WindowEvent e) {
           }

           @Override
           public void windowClosing(WindowEvent e) {
           }

           @Override
           public void windowClosed(WindowEvent e) {
               
                tipovenda = consultatipovenda.GetTipoVenda();
                
                
                if(tipovenda.getIdTipoVenda() > 0){
                    
                    String dados;
                    //Vendas v = new Vendas();
                    VendasController contr = new VendasController();
                    //v.setIdTipoVenda(Integer.parseInt(campoTipoVenda.getText()));
                    //dados = contr.pesquisaTipoVenda(v.getIdTipoVenda());
                    dados = contr.pesquisaTipoVenda(tipovenda.getIdTipoVenda());
                    if( dados != null){
                        campoNomeTipoVenda.setText(dados);
                        campoTipoVenda.setText(Integer.toString(tipovenda.getIdTipoVenda()));
                    }else{
                        campoNomeTipoVenda.setText("");
                        JOptionPane.showMessageDialog(null,"Código de Tipo de Venda não localizado");
                    }
                    //v = null;
                    contr = null;
                }
               
           }

           @Override
           public void windowIconified(WindowEvent e) {
           }

           @Override
           public void windowDeiconified(WindowEvent e) {
           }

           @Override
           public void windowActivated(WindowEvent e) {
           }

           @Override
           public void windowDeactivated(WindowEvent e) {
           }
       });
       consultatipovenda.setVisible(true);
        
    }//GEN-LAST:event_botaoPesquisaTipoVendaActionPerformed

    private void botaoPesquisaFormaPagtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisaFormaPagtoActionPerformed
        // TODO add your handling code here:
        /*String dados;
        Vendas v = new Vendas();
        VendasController contr = new VendasController();
        v.setIdFormaPagto(Integer.parseInt(campoFormaPagto.getText()));
        dados = contr.pesquisaFormaPagto(v.getIdFormaPagto());
        if( dados != null){
            campoNomeFormaPagto.setText(dados);
        }else{
            campoNomeFormaPagto.setText("");
            JOptionPane.showMessageDialog(null,"Código de Forma de Pagamento não localizado");
        }
        v = null;
        contr = null;*/
        
        ConsultaFormaPagto consultaformapagto = new ConsultaFormaPagto(formapagto);
        
        consultaformapagto.addWindowListener(new WindowListener() {
           @Override
           public void windowOpened(WindowEvent e) {
           }

           @Override
           public void windowClosing(WindowEvent e) {
           }

           @Override
           public void windowClosed(WindowEvent e) {
               
                formapagto = consultaformapagto.GetFormaPagto();
                
                
                if(formapagto.getIdFormaPagto() > 0){
                    
                    String dados;
                    //Vendas v = new Vendas();
                    VendasController contr = new VendasController();
                    //v.setIdFormaPagto(Integer.parseInt(campoFormaPagto.getText()));
                    //dados = contr.pesquisaFormaPagto(v.getIdFormaPagto());
                    dados = contr.pesquisaFormaPagto(formapagto.getIdFormaPagto());
                    if( dados != null){
                        campoNomeFormaPagto.setText(dados);
                        campoFormaPagto.setText(Integer.toString(formapagto.getIdFormaPagto()));
                    }else{
                        campoNomeFormaPagto.setText("");
                        JOptionPane.showMessageDialog(null,"Código de Forma de Pagamento não localizado");
                    }
                    //v = null;
                    contr = null;
                }
               
           }

           @Override
           public void windowIconified(WindowEvent e) {
           }

           @Override
           public void windowDeiconified(WindowEvent e) {
           }

           @Override
           public void windowActivated(WindowEvent e) {
           }

           @Override
           public void windowDeactivated(WindowEvent e) {
           }
       });
       consultaformapagto.setVisible(true);
        
        
    }//GEN-LAST:event_botaoPesquisaFormaPagtoActionPerformed

    private void campoCodClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodClienteFocusLost
        // TODO add your handling code here:
        if(!(campoCodCliente.getText()).isEmpty()){
            String dados;
            Vendas v = new Vendas();
            VendasController contr = new VendasController();
            v.setIdCliente(Integer.parseInt(campoCodCliente.getText()));
            dados = contr.pesquisaCliente(v.getIdCliente());
            if( dados != null){
                campoNomeCliente.setText(dados);
            }else{
                campoNomeCliente.setText("");
                JOptionPane.showMessageDialog(null,"Código de Cliente não localizado");
                campoCodCliente.requestFocus();
            }
            v = null;
            contr = null;
        }else{
            campoNomeCliente.setText("");
        }
    }//GEN-LAST:event_campoCodClienteFocusLost

    private void campoTipoVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTipoVendaFocusLost
        // TODO add your handling code here:
        if(!(campoTipoVenda.getText()).isEmpty()){
            String dados;
            Vendas v = new Vendas();
            VendasController contr = new VendasController();
            v.setIdTipoVenda(Integer.parseInt(campoTipoVenda.getText()));
            dados = contr.pesquisaTipoVenda(v.getIdTipoVenda());
            if( dados != null){
                campoNomeTipoVenda.setText(dados);
            }else{
                campoNomeTipoVenda.setText("");
                JOptionPane.showMessageDialog(null,"Código de Tipo de Venda não localizado");
                campoTipoVenda.requestFocus();
            }
            v = null;
            contr = null;
        }else{
            campoNomeTipoVenda.setText("");
        }
    }//GEN-LAST:event_campoTipoVendaFocusLost

    private void campoFormaPagtoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoFormaPagtoFocusLost
        // TODO add your handling code here:
        if(!(campoFormaPagto.getText()).isEmpty()){
            String dados;
            Vendas v = new Vendas();
            VendasController contr = new VendasController();
            v.setIdFormaPagto(Integer.parseInt(campoFormaPagto.getText()));
            dados = contr.pesquisaFormaPagto(v.getIdFormaPagto());
            if( dados != null){
                campoNomeFormaPagto.setText(dados);
            }else{
                campoNomeFormaPagto.setText("");
                JOptionPane.showMessageDialog(null,"Código de Forma de Pagamento não localizado");
                campoFormaPagto.requestFocus();
            }
            v = null;
            contr = null;
        }else{
            campoNomeFormaPagto.setText("");
        }
    }//GEN-LAST:event_campoFormaPagtoFocusLost

    private void campoCodClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodClienteActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        // TODO add your handling code here:
        botaoIncluir.setEnabled(false);
        botaoExcluir.setEnabled(false);
        botaoEditar.setEnabled(false);
        botaoCancelar.setEnabled(true);
        botaoGravarVenda.setEnabled(true);
        campoCodVenda.setEnabled(false);
        botaoPesquisaVenda.setEnabled(false);
        botaoSair.setEnabled(false);
        
        campoCodCliente.setEnabled(true);
        campoNomeCliente.setEnabled(false);
        botaoPesquisaCliente.setEnabled(true);
        campoTipoVenda.setEnabled(true);
        campoNomeTipoVenda.setEnabled(false);
        botaoPesquisaTipoVenda.setEnabled(true);
        campoFormaPagto.setEnabled(true);
        campoNomeFormaPagto.setEnabled(false);
        botaoPesquisaFormaPagto.setEnabled(true);
        campoDataVenda.setEnabled(true);
        campoDataVenda.setEditable(true);
        campoTotalVenda.setEnabled(true);
        campoTotalVenda.setEditable(false);
        
        campoCodProduto.setText("");
        campoNomeProduto.setText("");
        campoQntProduto.setText("");
        campoValorUnitProduto.setText("");
        campoValorTotalProduto.setText("");
        
        campoCodProduto.setEnabled(false);
        campoNomeProduto.setEnabled(false);
        campoQntProduto.setEnabled(false);
        campoValorUnitProduto.setEnabled(false);
        campoValorTotalProduto.setEnabled(false);
        botaoIncluirProduto.setEnabled(true);
        botaoExcluirProduto.setEnabled(false);
        botaoCancelarProduto.setEnabled(false);
        botaoGravarProduto.setEnabled(false);
        botaoPesquisarProduto.setEnabled(false);
        
        tabelaProdutos.setEnabled(true);
        
        
        
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esta venda ?", title, JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            VendasController contr = new VendasController();
            contr.delete(idVendaAtual);
            contr = null;
            campoCodVenda.setEnabled(true);
            botaoPesquisaVenda.setEnabled(true);
            campoCodCliente.setEnabled(false);
            campoNomeCliente.setEnabled(false);
            botaoPesquisaCliente.setEnabled(false);
            campoTipoVenda.setEnabled(false);
            campoNomeTipoVenda.setEnabled(false);
            botaoPesquisaTipoVenda.setEnabled(false);
            campoFormaPagto.setEnabled(false);
            campoNomeFormaPagto.setEnabled(false);
            botaoPesquisaFormaPagto.setEnabled(false);
            campoDataVenda.setEnabled(false);
            campoTotalVenda.setEnabled(false);
            botaoCancelar.setEnabled(false);
            botaoGravarVenda.setEnabled(false);
            botaoIncluir.setEnabled(true);
            botaoSair.setEnabled(true);
            botaoExcluir.setEnabled(false);
            botaoEditar.setEnabled(false);

            campoCodVenda.setText("");
            campoCodCliente.setText("");
            campoNomeCliente.setText("");
            campoTipoVenda.setText("");
            campoNomeTipoVenda.setText("");
            campoFormaPagto.setText("");
            campoNomeFormaPagto.setText("");
            //campoDataVenda.removeAll();
            campoTotalVenda.setText("");
            
            idVendaAtual = 0;
            preencheTabela(idVendaAtual);
        }
        
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoGravarVendaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_botaoGravarVendaInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoGravarVendaInputMethodTextChanged

    private void botaoExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirProdutoActionPerformed
        // TODO add your handling code here:
        
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir este produto ?\n A exclusão do item será permanente.", title, JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            
            VendasController contr = new VendasController();
        
            campoCodProduto.setText("");
            campoNomeProduto.setText("");
            campoQntProduto.setText("");
            campoValorUnitProduto.setText("");
            campoValorTotalProduto.setText("");

            campoCodProduto.setEnabled(false);
            campoNomeProduto.setEnabled(false);
            campoQntProduto.setEnabled(false);
            campoValorUnitProduto.setEnabled(false);
            campoValorTotalProduto.setEnabled(false);
            botaoIncluirProduto.setEnabled(true);
            botaoExcluirProduto.setEnabled(false);
            botaoCancelarProduto.setEnabled(false);
            botaoGravarProduto.setEnabled(false);
            botaoPesquisarProduto.setEnabled(false);
            
            contr.deleteItem(idProdutoClicado);
            campoTotalVenda.setText(valorFormatado.format(contr.atualizaTotal(idVendaAtual)));
            preencheTabela(idVendaAtual);
        }
        
    }//GEN-LAST:event_botaoExcluirProdutoActionPerformed

    private void botaoIncluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIncluirProdutoActionPerformed
        // TODO add your handling code here:
        
        campoCodProduto.setText("");
        campoNomeProduto.setText("");
        campoQntProduto.setText("");
        campoValorUnitProduto.setText("");
        campoValorTotalProduto.setText("");
        
        campoCodProduto.setEnabled(true);
        campoNomeProduto.setEnabled(true);
        campoQntProduto.setEnabled(true);
        campoValorUnitProduto.setEnabled(true);
        campoValorTotalProduto.setEnabled(true);
        botaoIncluirProduto.setEnabled(false);
        botaoExcluirProduto.setEnabled(false);
        botaoCancelarProduto.setEnabled(true);
        botaoGravarProduto.setEnabled(true);
        botaoPesquisarProduto.setEnabled(true);
        
        
    }//GEN-LAST:event_botaoIncluirProdutoActionPerformed

    private void botaoCancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarProdutoActionPerformed
        // TODO add your handling code here:
        
        campoCodProduto.setText("");
        campoNomeProduto.setText("");
        campoQntProduto.setText("");
        campoValorUnitProduto.setText("");
        campoValorTotalProduto.setText("");
        
        campoCodProduto.setEnabled(false);
        campoNomeProduto.setEnabled(false);
        campoQntProduto.setEnabled(false);
        campoValorUnitProduto.setEnabled(false);
        campoValorTotalProduto.setEnabled(false);
        botaoIncluirProduto.setEnabled(true);
        botaoExcluirProduto.setEnabled(false);
        botaoCancelarProduto.setEnabled(false);
        botaoGravarProduto.setEnabled(false);
        botaoPesquisarProduto.setEnabled(false);
        
        
        
    }//GEN-LAST:event_botaoCancelarProdutoActionPerformed

    private void botaoGravarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoGravarProdutoActionPerformed
        // TODO add your handling code here:
        
        if(!(campoNomeProduto.getText()).isEmpty() && !(campoQntProduto.getText()).isEmpty() && !(campoValorUnitProduto.getText()).isEmpty() && !(campoValorTotalProduto.getText().isEmpty())){
        ItemVenda p = new ItemVenda();
        VendasController contr = new VendasController();

        p.setCodProduto(Integer.parseInt(campoCodProduto.getText()));
        p.setNomeProd(campoNomeProduto.getText());
        p.setCodVenda(idVendaAtual);
        p.setQuantidade(Integer.parseInt(campoQntProduto.getText()));
        p.setValorUnit(Float.parseFloat((campoValorUnitProduto.getText()).replaceAll(",", ".")));
        p.setValorTotal(Float.parseFloat((campoValorTotalProduto.getText()).replaceAll(",", ".")));

        contr.createItem(p);
        
        campoCodProduto.setText("");
        campoNomeProduto.setText("");
        campoQntProduto.setText("");
        campoValorUnitProduto.setText("");
        campoValorTotalProduto.setText("");
        
        campoCodProduto.setEnabled(false);
        campoNomeProduto.setEnabled(false);
        campoQntProduto.setEnabled(false);
        campoValorUnitProduto.setEnabled(false);
        campoValorTotalProduto.setEnabled(false);
        botaoIncluirProduto.setEnabled(true);
        botaoExcluirProduto.setEnabled(false);
        botaoCancelarProduto.setEnabled(false);
        botaoGravarProduto.setEnabled(false);
        botaoPesquisarProduto.setEnabled(false);

        campoTotalVenda.setText(valorFormatado.format(contr.atualizaTotal(idVendaAtual)));
        preencheTabela(idVendaAtual);
        
        p = null;
        contr = null;
        
      }else{
          JOptionPane.showMessageDialog(null,"Preenchimento de todos os campos obrigatório !");
      }
        
    }//GEN-LAST:event_botaoGravarProdutoActionPerformed

    private void campoCodProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodProdutoFocusLost
        // TODO add your handling code here:
        
        if(!(campoCodProduto.getText()).isEmpty()){
            Produto dados;
            Produto p = new Produto();
            ProdutoController contr = new ProdutoController();
            p.setIdProduto(Integer.parseInt(campoCodProduto.getText()));
            dados = contr.pesquisaProduto(p.getIdProduto());
            if( dados != null){
                campoNomeProduto.setText(dados.getNomeProd());
            }else{
                campoNomeProduto.setText("");
                JOptionPane.showMessageDialog(null,"Produto não encontrado !");
                campoCodProduto.requestFocus();
            }
            p = null;
            contr = null;
        }else{
            campoNomeProduto.setText("");
        }
        
    }//GEN-LAST:event_campoCodProdutoFocusLost

    private void campoQntProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoQntProdutoFocusLost
        // TODO add your handling code here:
        if(!campoQntProduto.getText().isEmpty()){
            if(!campoValorUnitProduto.getText().isEmpty()){
                campoValorTotalProduto.setText("");
                campoValorTotalProduto.setText(valorFormatado.format(Integer.parseInt(campoQntProduto.getText()) * Float.parseFloat((campoValorUnitProduto.getText()).replaceAll(",", "."))));
            }else if(!campoValorTotalProduto.getText().isEmpty()){
                campoValorUnitProduto.setText("");
                campoValorUnitProduto.setText(valorFormatado.format(Float.parseFloat((campoValorTotalProduto.getText()).replaceAll(",", ".")) / Integer.parseInt(campoQntProduto.getText())));
            }
        }
        
        
    }//GEN-LAST:event_campoQntProdutoFocusLost

    private void campoValorUnitProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoValorUnitProdutoFocusLost
        // TODO add your handling code here:
        if(!campoValorUnitProduto.getText().isEmpty()){
            if(!campoQntProduto.getText().isEmpty()){
                campoValorTotalProduto.setText("");
                campoValorTotalProduto.setText(valorFormatado.format(Integer.parseInt(campoQntProduto.getText()) * Float.parseFloat((campoValorUnitProduto.getText()).replaceAll(",", "."))));
                campoValorUnitProduto.setText(valorFormatado.format(Float.parseFloat((campoValorUnitProduto.getText()).replaceAll(",", "."))));
            }
        }
        
        
    }//GEN-LAST:event_campoValorUnitProdutoFocusLost

    private void campoValorTotalProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoValorTotalProdutoFocusLost
        // TODO add your handling code here:
        
        if(!campoValorTotalProduto.getText().isEmpty()){
            if(!campoQntProduto.getText().isEmpty()){
                campoValorUnitProduto.setText("");
                campoValorUnitProduto.setText(valorFormatado.format(Float.parseFloat((campoValorTotalProduto.getText()).replaceAll(",", ".")) / Integer.parseInt(campoQntProduto.getText())));
                campoValorTotalProduto.setText(valorFormatado.format(Float.parseFloat((campoValorTotalProduto.getText()).replaceAll(",", "."))));
            }
        }
        
        
    }//GEN-LAST:event_campoValorTotalProdutoFocusLost

    private void campoQntProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoQntProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoQntProdutoActionPerformed

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
         // TODO add your handling code here:
        if (tabelaProdutos.getSelectedRow()!= -1){
            ItemVenda itemClicado = item.get(tabelaProdutos.getSelectedRow());
            idProdutoClicado = itemClicado.getIdVendaxproduto();
            botaoExcluirProduto.setEnabled(true);
            
        }
        
    }//GEN-LAST:event_tabelaProdutosMouseClicked

    private void tabelaProdutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaProdutosKeyReleased
        // TODO add your handling code here:
        if (tabelaProdutos.getSelectedRow()!= -1){
            ItemVenda itemClicado = item.get(tabelaProdutos.getSelectedRow());
            idProdutoClicado = itemClicado.getIdVendaxproduto();
            botaoExcluirProduto.setEnabled(true);
        }
        
    }//GEN-LAST:event_tabelaProdutosKeyReleased

    private void campoValorUnitProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoValorUnitProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoValorUnitProdutoActionPerformed

    private void campoTotalVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTotalVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTotalVendaActionPerformed

    private void campoCodVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCodVendaFocusLost
        // TODO add your handling code here:
        
        if(!(campoCodVenda.getText()).isEmpty()){
            Vendas dados;
            Vendas v = new Vendas();
            VendasController contr = new VendasController();
            v.setIdVenda(Integer.parseInt(campoCodVenda.getText()));
            dados = contr.pesquisaVenda(v.getIdVenda());
            if(dados != null){
                campoNomeCliente.setEnabled(true);
                campoNomeTipoVenda.setEnabled(true);
                campoNomeFormaPagto.setEnabled(true);
                campoDataVenda.setEnabled(true);
                campoDataVenda.setEditable(false);
                campoTotalVenda.setEnabled(true);
                campoTotalVenda.setEditable(false);
                botaoEditar.setEnabled(true);
                if(Geral.UsuarioLogado.getTipo().equals("Usuário")){
                    botaoExcluir.setEnabled(false);
                }
                else{
                    botaoExcluir.setEnabled(true);
                }

                campoCodVenda.setText(Integer.toString(v.getIdVenda()));
                campoDataVenda.setDate(dados.getDataVenda());
                campoCodCliente.setText(Integer.toString(dados.getIdCliente()));
                campoTotalVenda.setText(valorFormatado.format(dados.getValorTotal()));
                campoTipoVenda.setText(Integer.toString(dados.getIdTipoVenda()));
                campoFormaPagto.setText(Integer.toString(dados.getIdFormaPagto()));
                campoNomeCliente.setText(dados.getNomeCliente());
                campoNomeTipoVenda.setText(dados.getNomeTipoVenda());
                campoNomeFormaPagto.setText(dados.getNomeFormaPagto());
                idVendaAtual = venda.getIdVenda();
                tabelaProdutos.setEnabled(false);
                preencheTabela(idVendaAtual);
            }else{
                campoCodCliente.setText("");
                campoNomeCliente.setText("");
                campoTipoVenda.setText("");
                campoNomeTipoVenda.setText("");
                campoFormaPagto.setText("");
                campoNomeFormaPagto.setText("");
                //campoDataVenda.removeAll();
                campoTotalVenda.setText("");
                campoNomeCliente.setEnabled(false);
                campoNomeTipoVenda.setEnabled(false);
                campoNomeFormaPagto.setEnabled(false);
                campoDataVenda.setEnabled(false);
                campoTotalVenda.setEnabled(false);
                botaoEditar.setEnabled(false);
                botaoExcluir.setEnabled(false);
                
                botaoIncluirProduto.setEnabled(false);
                botaoExcluirProduto.setEnabled(false);
                botaoCancelarProduto.setEnabled(false);
                botaoGravarProduto.setEnabled(false);
                botaoPesquisarProduto.setEnabled(false);
                
                campoCodVenda.requestFocus();
                
                idVendaAtual = 0;
                preencheTabela(idVendaAtual);
                
                JOptionPane.showMessageDialog(null,"Código de Venda não localizado");
            }
            v = null;
            contr = null;
        }
        
        
    }//GEN-LAST:event_campoCodVendaFocusLost

    private void botaoPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarProdutoActionPerformed
        // TODO add your handling code here:

        ConsultaProduto consultaproduto = new ConsultaProduto(produto);

        consultaproduto.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
            }

            @Override
            public void windowClosed(WindowEvent e) {

                produto = consultaproduto.GetProduto();

                if(produto.getIdProduto() > 0){
                    Produto dados;
                    //Produto p = new Produto();
                    ProdutoController contr = new ProdutoController();
                    //p.setIdProduto(Integer.parseInt(campoCodProduto.getText()));
                    //dados = contr.pesquisaProduto(p.getIdProduto());
                    dados = contr.pesquisaProduto(produto.getIdProduto());
                    if( dados != null){
                        campoNomeProduto.setText(dados.getNomeProd());
                        campoCodProduto.setText(Integer.toString(produto.getIdProduto()));
                    }else{
                        campoNomeProduto.setText("");
                        JOptionPane.showMessageDialog(null,"Produto não encontrado !");
                        campoCodProduto.requestFocus();
                    }
                    //p = null;
                    contr = null;
                }

            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
        consultaproduto.setVisible(true);

    }//GEN-LAST:event_botaoPesquisarProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoCancelarProduto;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoExcluirProduto;
    private javax.swing.JButton botaoGravarProduto;
    private javax.swing.JButton botaoGravarVenda;
    private javax.swing.JButton botaoIncluir;
    private javax.swing.JButton botaoIncluirProduto;
    private javax.swing.JButton botaoPesquisaCliente;
    private javax.swing.JButton botaoPesquisaFormaPagto;
    private javax.swing.JButton botaoPesquisaTipoVenda;
    private javax.swing.JButton botaoPesquisaVenda;
    private javax.swing.JButton botaoPesquisarProduto;
    private javax.swing.JButton botaoSair;
    private javax.swing.JTextField campoCodCliente;
    private javax.swing.JTextField campoCodProduto;
    private javax.swing.JTextField campoCodVenda;
    private org.jdesktop.swingx.JXDatePicker campoDataVenda;
    private javax.swing.JTextField campoFormaPagto;
    private javax.swing.JTextField campoNomeCliente;
    private javax.swing.JTextField campoNomeFormaPagto;
    private javax.swing.JTextField campoNomeProduto;
    private javax.swing.JTextField campoNomeTipoVenda;
    private javax.swing.JTextField campoQntProduto;
    private javax.swing.JTextField campoTipoVenda;
    private javax.swing.JTextField campoTotalVenda;
    private javax.swing.JTextField campoValorTotalProduto;
    private javax.swing.JTextField campoValorUnitProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
