/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HBFTelas;

import Controller.EstoqueController;
import Model.Estoque;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Helen Reis
 */
public class Notificacoes extends javax.swing.JInternalFrame {
    EstoqueController estoqueController = new EstoqueController();

    /**
     * Creates new form Notificacoes
     */
    public Notificacoes() {
                initComponents();
        try {
            this.carregarAviso();
        } catch (SQLException ex) {
            Logger.getLogger(Notificacoes.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
            private void carregarAviso() throws SQLException{
        ArrayList<Estoque> estoqueArrayList = new ArrayList<>();

        JDesktopPane desk = new JDesktopPane();
        
        DefaultTableModel modelo = (DefaultTableModel) jtVendas.getModel();
        estoqueArrayList = estoqueController.getListaAviso();
        int count = estoqueArrayList.size();
        for(int i=0; i<count; i++) {
            modelo.addRow(new Object[]{
                estoqueArrayList.get(i).getProdutoId(),
                estoqueArrayList.get(i).getLdescricao(),
                estoqueArrayList.get(i).getQuantidade()+" unidades",
                estoqueArrayList.get(i).getLqtdemin()+" unidades"
  
            });

            
        }
    }
            
            public void setPosicao() {
                Dimension d = this.getDesktopPane().getSize();
                this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtVendas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jtVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Produto", "Descrição", "Qtde. Disponível", "Qtde. Mínima"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtVendas;
    // End of variables declaration//GEN-END:variables
}
