/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HBFTelas;

import Conexao.TestandoRelatorios;
import Controller.ProdutoController;
import Model.Categorias;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author User
 */
public class RelatorioEstoque extends javax.swing.JInternalFrame {

    /**
     * Creates new form RelatorioEstoque
     */
    public RelatorioEstoque() {
        initComponents();
        
        gerarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBoxCategoria = new javax.swing.JComboBox<>();
        GerarRelatorioEstoque = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CancelarRelatorioEstoque = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Relatório de Estoque");

        GerarRelatorioEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatório.jpg"))); // NOI18N
        GerarRelatorioEstoque.setText("Gerar Relatório");
        GerarRelatorioEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarRelatorioEstoqueActionPerformed(evt);
            }
        });

        jLabel1.setText("Categoria:");

        CancelarRelatorioEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair.png"))); // NOI18N
        CancelarRelatorioEstoque.setText("Sair");
        CancelarRelatorioEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarRelatorioEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GerarRelatorioEstoque)
                        .addGap(18, 18, 18)
                        .addComponent(CancelarRelatorioEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GerarRelatorioEstoque)
                    .addComponent(CancelarRelatorioEstoque))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GerarRelatorioEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarRelatorioEstoqueActionPerformed
        // TODO add your handling code here:
         TestandoRelatorios teste = new TestandoRelatorios();
            //System.out.println("abrindo.... ");
        try {
            String caminho = "C:\\Users\\User\\Documents\\GitHub\\Projetos\\src\\Relatorio\\";//caminho que está os relatório na maquina
            String arquivo = "RelatorioEstoque";//nome do arquivo do relatorio
            String categoria = (String)ComboBoxCategoria.getSelectedItem();//buscando do comboBox e setando a categoria
            ProdutoController pc = new ProdutoController();
            int codigo = pc.pesquisaCategoriasNome(categoria);
            String parametro = "codCat";
                teste.gerarRelatorio(caminho, arquivo, parametro, codigo);
            
        }catch(SQLException | ClassNotFoundException | JRException e){
            System.out.println(e.getMessage());
            
        } 
    }//GEN-LAST:event_GerarRelatorioEstoqueActionPerformed

    private void CancelarRelatorioEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarRelatorioEstoqueActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarRelatorioEstoqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelarRelatorioEstoque;
    private javax.swing.JComboBox<String> ComboBoxCategoria;
    private javax.swing.JButton GerarRelatorioEstoque;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
public void gerarCombo(){//Método para preencher todas as categorias no combo box
    ProdutoController pc = new ProdutoController();
    List<Categorias> lista = pc.readCategorias();
    lista.forEach((c) -> {
        ComboBoxCategoria.addItem(c.getNomeCat());
        });
}
}
