/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HBFTelas;

import Conexao.TestandoRelatorios;
import Model.Geral;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Rafael
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpprincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menucadastroProdutos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuVendas = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemMenuRelatorioEstoque = new javax.swing.JMenuItem();
        itemMenuRelatorioDeVendas = new javax.swing.JMenuItem();
        MenuDespesa = new javax.swing.JMenu();
        CadastroDespesa = new javax.swing.JMenuItem();
        botaoLogOut = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Mercadorias HBF");

        javax.swing.GroupLayout jdpprincipalLayout = new javax.swing.GroupLayout(jdpprincipal);
        jdpprincipal.setLayout(jdpprincipalLayout);
        jdpprincipalLayout.setHorizontalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1245, Short.MAX_VALUE)
        );
        jdpprincipalLayout.setVerticalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        menucadastroProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Novo.png"))); // NOI18N
        menucadastroProdutos.setText("Cadastros");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        jMenuItem1.setText("Cadastro de Usuario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menucadastroProdutos.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/designer.png"))); // NOI18N
        jMenuItem2.setText("Cadastro de Produtos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menucadastroProdutos.add(jMenuItem2);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/contract.png"))); // NOI18N
        jMenuItem6.setText("Cadastro de Estoque");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menucadastroProdutos.add(jMenuItem6);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group.png"))); // NOI18N
        jMenuItem3.setText("Cadastro de Clientes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menucadastroProdutos.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/group.png"))); // NOI18N
        jMenuItem4.setText("Cadastro de Fornecedor");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menucadastroProdutos.add(jMenuItem4);

        jMenuBar1.add(menucadastroProdutos);

        MenuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/stats.png"))); // NOI18N
        MenuVendas.setText("Vendas");
        MenuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVendasActionPerformed(evt);
            }
        });

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/incomes.png"))); // NOI18N
        jMenuItem5.setText("Controle de Vendas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuVendas.add(jMenuItem5);

        jMenuBar1.add(MenuVendas);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/page.png"))); // NOI18N
        jMenu2.setText("Relatorios");

        itemMenuRelatorioEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconeestoque.jpg"))); // NOI18N
        itemMenuRelatorioEstoque.setText("Relatório de Estoque");
        itemMenuRelatorioEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRelatorioEstoqueActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuRelatorioEstoque);

        itemMenuRelatorioDeVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sales.png"))); // NOI18N
        itemMenuRelatorioDeVendas.setText("Relatório de Vendas");
        itemMenuRelatorioDeVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRelatorioDeVendasActionPerformed(evt);
            }
        });
        jMenu2.add(itemMenuRelatorioDeVendas);

        jMenuBar1.add(jMenu2);

        MenuDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/list.png"))); // NOI18N
        MenuDespesa.setText("Despesa");

        CadastroDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/incomes.png"))); // NOI18N
        CadastroDespesa.setText("Controle Despesa");
        CadastroDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroDespesaActionPerformed(evt);
            }
        });
        MenuDespesa.add(CadastroDespesa);

        jMenuBar1.add(MenuDespesa);

        botaoLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/door_out.png"))); // NOI18N
        botaoLogOut.setText("LogOut");
        botaoLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLogOutMouseClicked(evt);
            }
        });
        botaoLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLogOutActionPerformed(evt);
            }
        });
        jMenuBar1.add(botaoLogOut);

        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Sair.png"))); // NOI18N
        MenuSair.setText("Sair");
        MenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(MenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpprincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpprincipal)
        );

        setBounds(30, 15, 1261, 701);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
        if(Geral.UsuarioLogado.getTipo().equals("Usuário"))
        {
            JOptionPane.showMessageDialog(null, "Usuario sem permissao.");
            return;
        }
        
        CadastroUsuario obj = new CadastroUsuario();
        // tela.show();
        // CadastroUsuario obj = new CadastroUsuario();
        jdpprincipal.add(obj);
        obj.setVisible(true);
     // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CadastroProduto obj = new CadastroProduto();
        jdpprincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CadastroVendas obj = new CadastroVendas();
        jdpprincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void MenuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuVendasActionPerformed

    private void MenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSairMouseClicked
        
        System.exit(0);
    }//GEN-LAST:event_MenuSairMouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        CadastroEstoque obj = new CadastroEstoque();
        jdpprincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        CadastroCliente obj = new CadastroCliente();
        jdpprincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        CadastroFornecedor obj = new CadastroFornecedor();
        jdpprincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void botaoLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLogOutActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botaoLogOutActionPerformed

    private void botaoLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLogOutMouseClicked
        // TODO add your handling code here:
        TelaLogin obj = new TelaLogin();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoLogOutMouseClicked

    private void itemMenuRelatorioEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRelatorioEstoqueActionPerformed
        // TODO add your handling code here:
       
        RelatorioEstoque re = new RelatorioEstoque();
        jdpprincipal.add(re);
        re.setVisible(true);
    }//GEN-LAST:event_itemMenuRelatorioEstoqueActionPerformed

    private void CadastroDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroDespesaActionPerformed
        CadastroDespesa obj = new CadastroDespesa();
        jdpprincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_CadastroDespesaActionPerformed

    private void itemMenuRelatorioDeVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRelatorioDeVendasActionPerformed
        
        RelatórioVenda rv = new RelatórioVenda();
        jdpprincipal.add(rv);
        rv.setVisible(true);
        
    }//GEN-LAST:event_itemMenuRelatorioDeVendasActionPerformed

    /**     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadastroDespesa;
    private javax.swing.JMenu MenuDespesa;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenu MenuVendas;
    private javax.swing.JMenu botaoLogOut;
    private javax.swing.JMenuItem itemMenuRelatorioDeVendas;
    private javax.swing.JMenuItem itemMenuRelatorioEstoque;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JDesktopPane jdpprincipal;
    private javax.swing.JMenu menucadastroProdutos;
    // End of variables declaration//GEN-END:variables
}
