/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HBFTelas;
import Controller.UsuarioController;
import Model.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class TelaConsultaUsuario extends javax.swing.JInternalFrame {

    //ArrayList valores = new ArrayList();//criação da arrayList para salvar os dados na tabela
    //int posicao=0;//Criei a posição para reconhecer qual posição da tabela foi selecionada
    
    /**
     * Creates new form TelaConsultaUsuario
     */
    public TelaConsultaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoCadastroNome = new javax.swing.JTextField();
        campoSenhaNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoInserirUsuario = new javax.swing.JButton();
        botaoApagarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();
        checkBoxUsuario = new javax.swing.JCheckBox();
        botaoAlterarUsuario = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro Usuário");

        campoCadastroNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCadastroNomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Senha:");

        botaoInserirUsuario.setText("Inserir");
        botaoInserirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInserirUsuarioActionPerformed(evt);
            }
        });

        botaoApagarUsuario.setText("Apagar");
        botaoApagarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoApagarUsuarioActionPerformed(evt);
            }
        });

        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo"
            }
        ));
        tabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaUsuario);

        checkBoxUsuario.setText("Administrador");

        botaoAlterarUsuario.setText("Alterar");
        botaoAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlterarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkBoxUsuario)
                                    .addComponent(campoSenhaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botaoInserirUsuario)
                                        .addGap(45, 45, 45)
                                        .addComponent(botaoApagarUsuario)
                                        .addGap(44, 44, 44)
                                        .addComponent(botaoAlterarUsuario))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoSenhaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkBoxUsuario)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoInserirUsuario)
                    .addComponent(botaoApagarUsuario)
                    .addComponent(botaoAlterarUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoInserirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInserirUsuarioActionPerformed
        String nome = campoCadastroNome.getText().trim();//gravando o que esta no campo para a variavel senha
        String senha = campoSenhaNome.getText().trim();//gravando o que esta no campo para a variavel senha
        String tipo = "";
       
        if(nome.isEmpty()){//Verificando se o Campo nome esta com algum valor
            JOptionPane.showMessageDialog(null, "Por favor insira o nome");
            return;
        }
        else if(senha.isEmpty()){//Verificando se o Campo senha esta com algum valor
            JOptionPane.showMessageDialog(null, "Por favor insira a senha");
            return;
        }
        
        Usuario u = new Usuario();
        UsuarioController ucontroller = new UsuarioController();
        u.setNomeUsuario(nome);//passando para o objeto o nome digitado no campo nome
        u.setSenhaUsuario(senha);//passando para o objeto a senha digitado no campo senha
        if (checkBoxUsuario.isSelected()){//verificando se usuário é administrador ou usuário padrão
              tipo = "Administrador";
            }
        else{
               tipo = "Usuário";
            }
        u.setTipo(tipo);//passando para o objeto o tipo de usuário
        ucontroller.create(u);//colocando o objeto no Bando de dados
        
        DefaultTableModel val = (DefaultTableModel) tabelaUsuario.getModel();//val = valores da tabela
        val.addRow(new Object[]{u.getNomeUsuario(),u.getSenhaUsuario(),u.getTipo()});//((String[]) valores.get(valores.size()-1));
        campoCadastroNome.setText("");//apagando o campo nome
        campoSenhaNome.setText("");//apagando o campo Senha
        campoCadastroNome.requestFocus();//Voltar o codigo para o campo nome
        checkBoxUsuario.setSelected(false);//Desmarcando o chechBox
        nome="";
        senha="";
        
//        String nome = campoCadastroNome.getText().trim();//gravando o que esta no campo para a variavel senha
//        String senha = campoSenhaNome.getText().trim();//gravando o que esta no campo para a variavel senha
//        String tipo = "";
//        
//        if(nome.isEmpty()){//Verificando se o Campo nome esta com algum valor
//            JOptionPane.showMessageDialog(null, "Por favor insira o nome");
//            return;
//        }
//        else if(senha.isEmpty()){//Verificando se o Campo senha esta com algum valor
//            JOptionPane.showMessageDialog(null, "Por favor insira a senha");
//            return;
//        }
//        
//        
//            if (checkBoxUsuario.isSelected()){//verificando se usuário é administrador ou usuário padrão
//              tipo = "Administrador";
//            }
//            else{
//               tipo = "Usuário";
//            }
//            DefaultTableModel val = (DefaultTableModel) tabelaUsuario.getModel();//val = valores da tabela
//            valores.add(new String[]{nome,tipo,senha});//adicionando os dados na array
//            val.addRow((String[]) valores.get(valores.size()-1));
//            campoCadastroNome.setText("");//apagando o campo nome
//            campoSenhaNome.setText("");//apagando o campo Senha
//            campoCadastroNome.requestFocus();//Voltar o codigo para o campo nome
//            checkBoxUsuario.setSelected(false);//Desmarcando o chechBox
//        
//        nome="";
//        senha="";
          
    }//GEN-LAST:event_botaoInserirUsuarioActionPerformed

    private void campoCadastroNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCadastroNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCadastroNomeActionPerformed

    private void botaoApagarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoApagarUsuarioActionPerformed
//        posicao = tabelaUsuario.getSelectedRow();//Buscando o numero da posição da tabela que foi clicado no mouse
//        valores.remove(posicao);//removendo o valor da posição que está sendo buscada na tabela
//        ((DefaultTableModel) tabelaUsuario.getModel()).removeRow(tabelaUsuario.getSelectedRow());//removendo os valores da tabela
//        campoCadastroNome.setText("");//apagando o campo nome
//        campoSenhaNome.setText("");//apagando o campo Senha
//        campoCadastroNome.requestFocus();//Voltar o codigo para o campo nome
//        checkBoxUsuario.setSelected(false);//Desmarcando o chechBox
    }//GEN-LAST:event_botaoApagarUsuarioActionPerformed

    private void tabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaUsuarioMouseClicked

//            String Tipo="";
////////            String[] dados = (String[]) valores.get(tabelaUsuario.getSelectedRow());//Setando os dados da tabala no arraylist  
////////            campoCadastroNome.setText(dados[0]);//Recuperando da arreylist a senha
////////            campoSenhaNome.setText(dados[2]);//Recuperando da arreylist a senha
////////            Tipo=dados[1];//Recuperando da arrayList e salvando na variável Tipo 
////////            if(Tipo=="Administrador"){//se o tipo for administrador irá executar o if abaixo
////////                checkBoxUsuario.setSelected(true);//Fazando com que a check box fique marcada
////////            }
    }//GEN-LAST:event_tabelaUsuarioMouseClicked

    private void botaoAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlterarUsuarioActionPerformed
//       posicao = tabelaUsuario.getSelectedRow();//Buscando o numero da posição da tabela que foi clicado no mouse
//       String nome = campoCadastroNome.getText().trim();//gravando o que esta no campo para a variavel senha
//       String senha = campoSenhaNome.getText().trim();//gravando o que esta no campo para a variavel senha
//       String tipo = "";
//       if(nome.isEmpty()){//Verificando se o Campo nome esta com algum valor
//            JOptionPane.showMessageDialog(null, "Por favor insira o nome");
//            return;
//        }
//        else if(senha.isEmpty()){//Verificando se o Campo senha esta com algum valor
//            JOptionPane.showMessageDialog(null, "Por favor insira a senha");
//            return;
//        }
//       
//       if (checkBoxUsuario.isSelected()){//verificando se usuário é administrador ou usuário padrão
//              tipo = "Administrador";
//            }
//        else{
//               tipo = "Usuário";
//        }
//        DefaultTableModel val = (DefaultTableModel) tabelaUsuario.getModel();//val = valores da tabela
//        valores.remove(posicao);
//        valores.add(posicao,new String[]{nome,tipo,senha});//na posição que foi clicada é inserida
//        ((DefaultTableModel) tabelaUsuario.getModel()).removeRow(tabelaUsuario.getSelectedRow());//removendo os valores da tabela
//        val.addRow((String[]) valores.get(valores.size()-1));//inserir na tabela na posição que foi clicada
//        campoCadastroNome.setText("");//apagando o campo nome
//        campoSenhaNome.setText("");//apagando o campo Senha
//        campoCadastroNome.requestFocus();//Voltar o codigo para o campo nome
//        checkBoxUsuario.setSelected(false);//Desmarcando o chechBox
    }//GEN-LAST:event_botaoAlterarUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterarUsuario;
    private javax.swing.JButton botaoApagarUsuario;
    private javax.swing.JButton botaoInserirUsuario;
    private javax.swing.JTextField campoCadastroNome;
    private javax.swing.JTextField campoSenhaNome;
    private javax.swing.JCheckBox checkBoxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaUsuario;
    // End of variables declaration//GEN-END:variables
}
